<?php
/**
 * @file
 * druvel module
 *
 * Main module file and MVC entrypoint
 *
 * @package druvel
 * @author Luca Pitzoi <luca.pitzoi@sindria.org>
 * @version 0.1.0
 *
 */


require_once 'vendor/autoload.php';


/**
 * Implements hook_node_info()
 */
function druvel_node_info() {
    return Druvel_Utility_Config::configNodes();
}


/**
 * Implement hook_menu()
 */
function druvel_menu() {
    return Druvel_Http_Kernel::webRoutes();
}


/**
 * Wrapper callback for web routes MVC kernel handle
 */
function druvel_web_routes_wrapper() {
    $kernel = new Druvel_Http_Kernel();
    $kernel->webHandle();
}


/**
 * Custom preprocess to implement routing by node->type
 *
 * @param $vars
 */
function druvel_preprocess(&$vars) {
    $kernel = new Druvel_Http_Kernel();
    $kernel->typeHandle($vars);
}